import assert from 'node:assert/strict';
import {createLifeWorld, upgradeLifeWorld, moneyTotal, residentNetWorth} from '../app/life-sim/engine';
import {openingLiquidity} from '../app/life-sim/liquidity';
import {translate} from '../app/language';
import {VENUES} from '../app/life-sim/society';
const world=createLifeWorld();
for(const label of [...Object.values(world.businesses!).map(b=>b.name),...Object.values(world.housing!).map(h=>h.buildingName),...world.residents.flatMap(r=>[r.job,r.identity!.homeStatus,r.identity!.preference]),...VENUES.flatMap(v=>[v.name,v.kind])])assert(!/\p{Script=Han}/u.test(translate(label,'en')),`Untranslated generated label: ${label}`);
assert.equal(new Set(world.residents.map(r=>r.englishName)).size,3000);
assert(world.residents.every(r=>/^[A-Za-z .]+$/.test(r.englishName!)));
assert.equal(moneyTotal(world),world.openingMoney);
const old=structuredClone(world);delete old.liquidityVersion;
const r=old.residents[0],i=Number(r.id.slice(1))-1;
r.cash=12000+(i*913)%54000+10000;
r.savings=10000+(i*1771)%85000+300000;
const worth=old.residents.map(r=>residentNetWorth(r,old.minute));
const updated=upgradeLifeWorld(old);
assert.equal(moneyTotal(updated),moneyTotal(old));
assert.deepEqual(updated.residents.map(r=>residentNetWorth(r,updated.minute)),worth);
assert(updated.residents[0].cash>=10000);
assert(updated.residents[0].savings>=300000,'earned savings preserved');
assert.deepEqual(upgradeLifeWorld(updated),updated,'idempotent correction');
assert(openingLiquidity({...r,employment:{...r.employment!,monthlyGrossCents:150000}}).savings<=openingLiquidity({...r,employment:{...r.employment!,monthlyGrossCents:900000}}).savings);
for(const label of ['净财富后 50%','第 50–90 百分位','第 90–99 百分位','净财富前 1%',' 户自有住房',' 人口占比','财富份额'])assert(!/\p{Script=Han}/u.test(translate(label,'en')));
const boundaries=[0,.5,.9,.99,1];
assert.deepEqual(boundaries.slice(0,-1).map((n,i)=>Math.floor(3000*boundaries[i+1])-Math.floor(3000*n)),[1500,1200,270,30]);
console.log('PASS: English names, translated labels, population shares, liquidity migration and ledger conservation');
