import assert from 'node:assert/strict';
import {advanceLifeWorld,createLifeWorld,moneyTotal,residentNetWorth,upgradeLifeWorld} from '../app/life-sim/engine';
import {ingestMarketSnapshot,quoteReturn,validateMarketSnapshot} from '../app/life-sim/market-feed';
import {applyWorldEvent} from '../app/life-sim/world-events';
import {learnExperience,learnMarketOutcome,learnedMarketStyle,policyFor} from '../app/life-sim/adaptive-policy';

const market=(asOf:string,availableAt:string,aapl:number,msft:number)=>({asOf,availableAt,source:'test-fixture-not-live-data',quotes:{AAPL:aapl,MSFT:msft}});
const now='2026-09-23T12:00:00Z';
assert.throws(()=>validateMarketSnapshot(market('2026-09-25T20:00:00Z','2026-09-25T20:01:00Z',10000,20000),now),/Future/);
assert.throws(()=>validateMarketSnapshot(market('2026-09-20T20:00:00Z','2026-09-19T20:00:00Z',10000,20000),now),/before observation/);

let world=createLifeWorld();
assert.equal(world.residents.length,30000);
assert(world.residents.every(r=>Number.isFinite(r.stress)&&r.stress>=0&&r.stress<=100));
const learner=structuredClone(world.residents.find(r=>r.frugality<=.6&&r.risk>.55)!);
assert.equal(learnedMarketStyle(learner),'momentum');
policyFor(learner).entryStyle={AAPL:'momentum'};
for(let i=0;i<8;i++)learnMarketOutcome(learner,480+i*60,'AAPL',-.10);
assert.equal(learnedMarketStyle(learner),'contrarian','repeated losses should change the next search style');
assert(policyFor(learner).riskMultiplier<1,'losses should reduce position budget');
assert.equal(policyFor(learner).experiences.length,8,'experience trace must remain bounded');
const priorFood=policyFor(learner).freshFoodAffinity;
learnExperience(learner,1000,'food',.8,'fruit helped after a difficult day');
assert(policyFor(learner).freshFoodAffinity>priorFood,'food outcomes must change future food preference');
learnExperience(learner,1001,'family',-.9,'family argument');
assert(policyFor(learner).familySupport<0,'family memory must affect social context');
assert(policyFor(learner).riskMultiplier>=.4,'losses cannot create an unbounded policy');
world=applyWorldEvent(world,'Milk prices rise 20%');
assert.equal(Object.values(world.worldEvents!.at(-1)!.counts).reduce((sum,count)=>sum+count,0),30000);
const veteran=world.residents.find(r=>(r.identity?.age||0)>=65&&r.risk>.55&&r.frugality<=.6);
assert(veteran);
const topUp=50000-veteran.cash;
veteran.cash+=topUp;world.treasury-=topUp;
veteran.health=95;veteran.water=95;veteran.nutrition=95;veteran.energy=95;veteran.happiness=95;veteran.stress=20;
veteran.profile!.pantry=5;veteran.profile!.lastShopDay=0;
world.minute=16*60;
world=ingestMarketSnapshot(world,market('2026-09-20T20:00:00Z','2026-09-20T20:01:00Z',10000,20000),now);
world=ingestMarketSnapshot(world,market('2026-09-21T20:00:00Z','2026-09-21T20:01:00Z',10500,21000),now);
assert(Math.abs(quoteReturn(world.market!,'AAPL')!-.05)<1e-9);
assert.throws(()=>ingestMarketSnapshot(world,market('2026-09-21T20:00:00Z','2026-09-21T20:01:00Z',10500,21000),now),/monotonically/);
assert.throws(()=>ingestMarketSnapshot(world,{asOf:'2026-09-22T20:00:00Z',availableAt:'2026-09-22T20:01:00Z',source:'test',quotes:{AAPL:9000}},now),/Missing prior symbol/);
const cashBefore=moneyTotal(world);
world=advanceLifeWorld(world,60);
assert.equal(moneyTotal(world),cashBefore);
const trader=world.residents.find(r=>r.id===veteran.id)!;
assert.equal(trader.lastTradeAsOf,'2026-09-21T20:00:00Z');
assert(Object.values(trader.holdings||{}).some(quantity=>quantity>0),`resident should buy using available market data: ${trader.action}, ${trader.reason}, cash ${trader.cash}, remaining ${trader.remaining}`);
const stressBefore=trader.stress;
world=ingestMarketSnapshot(world,market('2026-09-22T20:00:00Z','2026-09-22T20:01:00Z',7000,14000),now);
assert(world.residents.find(r=>r.id===veteran.id)!.stress>stressBefore,'loss on held stock should raise stress');
assert((world.residents.find(r=>r.id===veteran.id)!.adaptivePolicy?.marketObservations||0)>0,'held-stock outcome should enter adaptive memory');
assert((world.residents.find(r=>r.id===veteran.id)!.adaptivePolicy?.riskMultiplier||1)<1,'loss should tighten the next position budget');
assert.equal(moneyTotal(world),cashBefore);
assert.throws(()=>ingestMarketSnapshot(world,{asOf:'2026-09-22T21:00:00Z',availableAt:'2026-09-22T21:01:00Z',source:'test',quotes:{AAPL:0,MSFT:14000}},now),/Invalid cent price/);
const worthBeforeDelisting=residentNetWorth(world.residents.find(r=>r.id===veteran.id)!,world.minute,world.market);
world=ingestMarketSnapshot(world,{asOf:'2026-09-22T21:00:00Z',availableAt:'2026-09-22T21:01:00Z',source:'test-delisting-fixture',quotes:{AAPL:0,MSFT:14000},delistedSymbols:['AAPL']},now);
assert.equal(quoteReturn(world.market!,'AAPL'),-1);
assert(residentNetWorth(world.residents.find(r=>r.id===veteran.id)!,world.minute,world.market)<worthBeforeDelisting);
const legacy=structuredClone(world);
delete (legacy.residents[0] as Partial<typeof legacy.residents[0]>).stress;
delete legacy.residents[0].holdings;
const migrated=upgradeLifeWorld(legacy);
assert.equal(migrated.residents[0].stress,30);
assert.deepEqual(migrated.residents[0].holdings,{});
assert.equal(migrated.residents[0].adaptivePolicy?.version,1);
assert.equal(migrated.residents[0].cash,legacy.residents[0].cash);
world=advanceLifeWorld(world,1440);
assert(world.socialEncounters?.some(item=>item.kind==='household-conflict'||item.kind==='household-support'),'household relationships should produce lived events');
assert(world.residents.every(r=>Number.isFinite(r.stress)&&r.stress>=0&&r.stress<=100),'stress must remain bounded for all residents');
assert.equal(moneyTotal(world),cashBefore);
console.log(JSON.stringify({passed:true,residents:world.residents.length,trader:trader.id,holdings:trader.holdings,householdEvents:world.socialEncounters?.length,conservedCents:moneyTotal(world)}));
