import assert from 'node:assert/strict';
import {advanceLifeWorld,createLifeWorld,moneyTotal,residentNetWorth,upgradeLifeWorld} from '../app/life-sim/engine';
import {ingestMarketSnapshot,quoteReturn,validateMarketSnapshot} from '../app/life-sim/market-feed';
import {applyWorldEvent} from '../app/life-sim/world-events';
import {learnExperience,learnMarketOutcome,learnedMarketStyle,policyFor} from '../app/life-sim/adaptive-policy';
import {ageWellbeing,applyPublicShock,populationWellbeingScores,updateWellbeing,wellbeingFor} from '../app/life-sim/wellbeing';

const market=(asOf:string,availableAt:string,aapl:number,msft:number)=>({asOf,availableAt,source:'test-fixture-not-live-data',quotes:{AAPL:aapl,MSFT:msft}});
const now='2026-09-23T12:00:00Z';
assert.throws(()=>validateMarketSnapshot(market('2026-09-25T20:00:00Z','2026-09-25T20:01:00Z',10000,20000),now),/Future/);
assert.throws(()=>validateMarketSnapshot(market('2026-09-20T20:00:00Z','2026-09-19T20:00:00Z',10000,20000),now),/before observation/);

let world=createLifeWorld();
assert.equal(world.residents.length,30000);
assert(world.residents.every(r=>Number.isFinite(r.stress)&&r.stress>=0&&r.stress<=100));
const steady=structuredClone(world.residents[0]);
steady.water=90;steady.nutrition=90;steady.energy=90;
const steadyHappiness=steady.happiness,steadyStress=steady.stress;
for(let day=0;day<30;day++){for(let tick=0;tick<288;tick++)updateWellbeing(steady);ageWellbeing(steady);}
assert(Math.abs(steady.happiness-steadyHappiness)<3&&steady.stress>=steadyStress&&steady.stress<steadyStress+10,'isolated no-event wellbeing should remain bounded');
applyPublicShock(steady,'negative',20,1);
assert(steady.happiness<steadyHappiness&&steady.stress>steadyStress&&wellbeingFor(steady).eventPressure>0);
for(let tick=0;tick<288;tick++)updateWellbeing(steady);
assert(steady.happiness<steadyHappiness,'a public shock should continue to weigh on wellbeing after a day');
const depressedHappiness=steady.happiness;
applyPublicShock(steady,'positive',20,1);
for(let tick=0;tick<288;tick++)updateWellbeing(steady);
assert(steady.happiness>depressedHappiness,'positive news should offset perceived pressure');
const learner=structuredClone(world.residents.find(r=>r.frugality<=.6&&r.risk>.55)!);
assert.equal(learnedMarketStyle(learner),'momentum');
policyFor(learner).entryStyle={AAPL:'momentum'};
for(let i=0;i<8;i++)learnMarketOutcome(learner,480+i*60,'AAPL',-.10);
assert.equal(learnedMarketStyle(learner),'contrarian','repeated losses should change the next search style');
assert(policyFor(learner).riskMultiplier<1,'losses should reduce position budget');
assert.equal(policyFor(learner).experiences.length,8,'experience trace must remain bounded');
const priorFood=policyFor(learner).freshFoodAffinity;
learnExperience(learner,1000,'food',.8,'fruit helped after a difficult day');
assert(policyFor(learner).freshFoodAffinity>priorFood,'food outcomes must change future food preference');
learnExperience(learner,1001,'family',-.9,'family argument');
assert(policyFor(learner).familySupport<0,'family memory must affect social context');
assert(policyFor(learner).riskMultiplier>=.4,'losses cannot create an unbounded policy');
const populationHappinessBefore=populationWellbeingScores(world.residents);
world=applyWorldEvent(world,'Milk prices rise 20%');
assert.equal(Object.values(world.worldEvents!.at(-1)!.counts).reduce((sum,count)=>sum+count,0),30000);
const populationAfter=populationWellbeingScores(world.residents);
assert(populationAfter.happiness<populationHappinessBefore.happiness&&populationAfter.mood<populationHappinessBefore.mood&&populationAfter.stressManagement<populationHappinessBefore.stressManagement,'price news may visibly change the full-city hexagon');
assert(world.residents.some(r=>(r.wellbeing?.eventPressure||0)>0),'news pressure is held per resident');
const oneResident={...world,residents:[structuredClone(world.residents[0])]},beforeWar=oneResident.residents[0].wellbeing!.mood;
const afterWar=applyWorldEvent(oneResident,'War breaks out');
assert(afterWar.residents[0].wellbeing!.mood<beforeWar,'non-financial negative news must affect wellbeing');
const afterPeace=applyWorldEvent(afterWar,'Peace treaty signed');
assert(afterPeace.residents[0].wellbeing!.eventPressure<afterWar.residents[0].wellbeing!.eventPressure,'positive news should offset accumulated pressure');
const wageNews=applyWorldEvent(afterWar,'Wages increase 20%');
assert(wageNews.worldEvents!.at(-1)!.tone==='positive'&&wageNews.residents[0].wellbeing!.eventPressure<afterWar.residents[0].wellbeing!.eventPressure,'income growth must not be confused with a price rise');
const veteran=world.residents.find(r=>(r.identity?.age||0)>=65&&r.risk>.55&&r.frugality<=.6);
assert(veteran);
const topUp=50000-veteran.cash;
veteran.cash+=topUp;world.treasury-=topUp;
veteran.health=95;veteran.water=95;veteran.nutrition=95;veteran.energy=95;veteran.happiness=95;veteran.stress=20;
veteran.profile!.pantry=5;veteran.profile!.lastShopDay=0;
world.minute=16*60;
world=ingestMarketSnapshot(world,market('2026-09-20T20:00:00Z','2026-09-20T20:01:00Z',10000,20000),now);
world=ingestMarketSnapshot(world,market('2026-09-21T20:00:00Z','2026-09-21T20:01:00Z',10500,21000),now);
assert(Math.abs(quoteReturn(world.market!,'AAPL')!-.05)<1e-9);
assert.throws(()=>ingestMarketSnapshot(world,market('2026-09-21T20:00:00Z','2026-09-21T20:01:00Z',10500,21000),now),/monotonically/);
assert.throws(()=>ingestMarketSnapshot(world,{asOf:'2026-09-22T20:00:00Z',availableAt:'2026-09-22T20:01:00Z',source:'test',quotes:{AAPL:9000}},now),/Missing prior symbol/);
const cashBefore=moneyTotal(world);
world=advanceLifeWorld(world,60);
assert.equal(moneyTotal(world),cashBefore);
const trader=world.residents.find(r=>r.id===veteran.id)!;
assert.equal(trader.lastTradeAsOf,'2026-09-21T20:00:00Z');
assert(Object.values(trader.holdings||{}).some(quantity=>quantity>0),`resident should buy using available market data: ${trader.action}, ${trader.reason}, cash ${trader.cash}, remaining ${trader.remaining}`);
const stressBefore=trader.stress;
world=ingestMarketSnapshot(world,market('2026-09-22T20:00:00Z','2026-09-22T20:01:00Z',7000,14000),now);
assert(world.residents.find(r=>r.id===veteran.id)!.stress>stressBefore,'loss on held stock should raise stress');
assert((world.residents.find(r=>r.id===veteran.id)!.adaptivePolicy?.marketObservations||0)>0,'held-stock outcome should enter adaptive memory');
assert((world.residents.find(r=>r.id===veteran.id)!.adaptivePolicy?.riskMultiplier||1)<1,'loss should tighten the next position budget');
assert.equal(moneyTotal(world),cashBefore);
assert.throws(()=>ingestMarketSnapshot(world,{asOf:'2026-09-22T21:00:00Z',availableAt:'2026-09-22T21:01:00Z',source:'test',quotes:{AAPL:0,MSFT:14000}},now),/Invalid cent price/);
const worthBeforeDelisting=residentNetWorth(world.residents.find(r=>r.id===veteran.id)!,world.minute,world.market);
world=ingestMarketSnapshot(world,{asOf:'2026-09-22T21:00:00Z',availableAt:'2026-09-22T21:01:00Z',source:'test-delisting-fixture',quotes:{AAPL:0,MSFT:14000},delistedSymbols:['AAPL']},now);
assert.equal(quoteReturn(world.market!,'AAPL'),-1);
assert(residentNetWorth(world.residents.find(r=>r.id===veteran.id)!,world.minute,world.market)<worthBeforeDelisting);
const legacy=structuredClone(world);
delete (legacy.residents[0] as Partial<typeof legacy.residents[0]>).stress;
delete legacy.residents[0].holdings;
const migrated=upgradeLifeWorld(legacy);
assert.equal(migrated.residents[0].stress,30);
assert.deepEqual(migrated.residents[0].holdings,{});
assert.equal(migrated.residents[0].adaptivePolicy?.version,1);
assert.equal(migrated.residents[0].cash,legacy.residents[0].cash);
world=advanceLifeWorld(world,1440);
assert(world.socialEncounters?.some(item=>item.kind==='household-conflict'||item.kind==='household-support'),'household relationships should produce lived events');
assert(world.residents.every(r=>Number.isFinite(r.stress)&&r.stress>=0&&r.stress<=100),'stress must remain bounded for all residents');
assert.equal(moneyTotal(world),cashBefore);
console.log(JSON.stringify({passed:true,residents:world.residents.length,trader:trader.id,holdings:trader.holdings,householdEvents:world.socialEncounters?.length,conservedCents:moneyTotal(world),beforeMilkNews:{happiness:Number(populationHappinessBefore.happiness.toFixed(2)),mood:Number(populationHappinessBefore.mood.toFixed(2)),stress:Number((100-populationHappinessBefore.stressManagement).toFixed(2))},afterMilkNews:{happiness:Number(populationAfter.happiness.toFixed(2)),mood:Number(populationAfter.mood.toFixed(2)),stress:Number((100-populationAfter.stressManagement).toFixed(2))}}));
